# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to save dungeon run loot info

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE

Resources:
    SaveDungeonRunLootInfoFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: save-dungeon-run-loot-info.default
            Runtime: nodejs10.x
            Timeout: 180
            MemorySize: 128
            CodeUri: ./dist/save-dungeon-run-loot-info
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-save-dungeon-run-loot-info
            Events:
                SaveDungeonRunLootInfoResource:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: any

Outputs:
    SaveDungeonRunLootInfoApi:
        Description: URL to save dungeon run loot info
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
        Export:
            Name: SaveDungeonRunLootInfoApi
